### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by Joey-Pepperoni** [tiekoetter/searxng#10]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.03.13-cd92a7ea (1d821b28)

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 0
  * Parameters: `('200', 'OK', 'www.mojeek.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

**Comment by tiekoetter** [comment]
Tracked in #9
