### ISSUE TITLE
Bug: startpage engine crash

### ISSUE THREAD

**Issue by qube-03** [tiekoetter/searxng#13]
this is most likely a result of the previous fix lol

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.04.06-4135a740 (a3be8020)

**How did you install SearXNG?**

i installed with the search engine helper add on for firefox
**What happened?**

i searched for 'ducks' and there was an error: "startpage: unexpected crash"

**How To Reproduce**

search for anything

**Expected behavior**

get normal search results, startpage included

**Technical report**

Error
  * Error: 2 redirects, maximum: 0
  * Percentage: 80
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

Error
  * Error: TypeError
  * Percentage: 10
  * Parameters: `('SearxEngineResponseException() takes no keyword arguments',)`
  * File name: `searx/engines/startpage.py:96`
  * Function: `get_sc_code`
  * Code: `raise SearxEngineResponseException(`

Error
  * Error: 1 redirects, maximum: 0
  * Percentage: 10
  * Parameters: `('200', 'OK', 'www.startpage.com')`
  * File name: `searx/search/processors/online.py:105`
  * Function: `_send_http_request`
  * Code: `count_error(`

**Comment by tiekoetter** [comment]
Startpage is currently broken on (almost) all public instances.
I will leave this issue open to remind me to work on it if I have time.

You can also contact me on [Matrix](https://matrix.to/#/#searxng:matrix.org) (official SearXNG group) and/or [Discord](https://discord.gg/JC7kzPMJmJ) if you want to further discuss this issue.

Best regards

**Comment by tiekoetter** [comment]
FYI a fix is on the way. https://github.com/searxng/searxng/pull/1126

**Comment by tiekoetter** [comment]
> FYI a fix is on the way. [searxng#1126](https://github.com/searxng/searxng/pull/1126)

PR was closed. I cherry-picked the commits so that startpage works again.
https://github.com/tiekoetter/searxng/commit/2fb031151de64a73901ece627e0683091be34a00

Closing
