### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by Kenoxys** [tiekoetter/searxng#14]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.04.17-e22dc2ba (9280a6c4)

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`
  

¡Error! Los motores no pueden obtener resultados:

mojeek ( [Suspendido/a: acceso denegado](https://searx.tiekoetter.com/stats?engine=mojeek) )

**Comment by tiekoetter** [comment]
Hi,
Sorry for the inconvenience; Mojeek blocked my proxy servers again.
I will try to fix it as soon as possible.

Best regards
