### ISSUE TITLE
Oscar theme not working. Settings got reset.

### ISSUE THREAD

**Issue by MagnetizedFreckles** [tiekoetter/searxng#18]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2022.05.03-31521f3a (7017450c)

**What happened?**
Today I got "Invalid settings, please edit your preferences" message and all my settings on all devices have been reset.
Also "oscar" theme disappeared from options list 

**How To Reproduce**
Idk.

**Expected behavior**
Oscar theme should be in options list.

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/81415404/166564102-66cbcc35-61ce-45f8-bbdc-3629632d75bf.png)
![image](https://user-images.githubusercontent.com/81415404/166564173-d251d9e8-3fde-4891-ad32-1494eb9286ab.png)

**Comment by MagnetizedFreckles** [comment]
Checked this https://github.com/searxng/searxng/discussions/1167
Understood that the support for oscar theme is dropped.
Sad now.

**Comment by tiekoetter** [comment]
I can understand that it probably isn't great to be forced to switch but I think the simple theme is far more superior than oscar.

If you have anything you think is missing from the simple theme please report it to the upstream repository.
