### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by AvianaDownloadLinux** [tiekoetter/searxng#21]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.05.20-61535a4c (c77d82bf)

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Hi @AvianaDownloadLinux
I can't reproduce your error (check https://searx.tiekoetter.com/search?q=%21ddg+test+%3Aen). Could you please fill out the rest of the form so that I know the context of the error?

**Comment by Elandig** [comment]
![image](https://user-images.githubusercontent.com/15586732/170239895-78ebe565-3aa0-4557-8bd3-0cd7f20b8991.png)
Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Practically any DDG search query on your searxng instance results in a 403 error.
