### ISSUE TITLE
Bug: No "General" results

### ISSUE THREAD

**Issue by qube-03** [tiekoetter/searxng#22]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.05.24-fddbc5ed (39077fc0)

**How did you install SearXNG?**
i installed ungoogled chromium on my android 12 device and set the website as my start page.
**What happened?**
i didnt get any search results besides images

**How To Reproduce**
search for anything, i used "ducks"

**Expected behavior**
search for "ducks" and get articles and websites like normal

**Screenshots & Logs**
![Screenshot_20220525-114138_Ungoogled Chromium](https://user-images.githubusercontent.com/92535344/170234501-edae0ad3-b54c-4d0d-9b66-4c69f6fad7d8.png)
![Screenshot_20220525-114145_Ungoogled Chromium](https://user-images.githubusercontent.com/92535344/170234574-ad12dc57-9f08-40f0-8a3a-807fe2952f26.png)

**Additional context**
now, this is only one of the engines that didnt bring any results, the only page that  showed up was a wikiless page that was already cached. in short; i didnt get any results besides images, maybe the server is down, maybe its a browser issue, idk. please resolve this so your instance can still be used! thank you in advance, ill include screenshots. this also started happening just an hour ago or so.

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 10
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by qube-03** [comment]
no clue why it was closed so quickly but i should add its an engine issue, the engines i used didnt work

**Comment by tiekoetter** [comment]
@qube-03 My instance was attacked by some bot(s). The upstream engines blocked my proxies as a result. I have now swapped all proxies. Everything should be working again.

**Comment by qube-03** [comment]
indeed it does, thanks!
