### ISSUE TITLE
Block certain results by using keywords (blacklist on options)

### ISSUE THREAD

**Issue by masterofobzene** [tiekoetter/searxng#23]
This is no critical feature:

Implement an option to remove certain results from searches by using phrases or keywords.
I'm actually using the [ublacklist extension that I modified to work with SEARX (firefox only)](https://github.com/masterofobzene/SearchBlocklist), and I know the "-" option in the search field to remove certain words but doing this takes more time when searching than simply searching for the intended words/phrase. Also ublacklist needs specific URLs to work so I would have to repeat the blocking on every bad result (that are probably auto-generated using search keywords so this wold be infinite).

**WHY?**
I'm really... really... REALLY tired of "toplists"; results like "5 Ways to....", "10 best softwares to...", "3 things..." etc etc.
Recently those websites started to pop-up like a virus on the net.

IDEA(?): An option that auto-concatenates certain "negative words" (i.e "-10 best") that the user can configure via settings so when searching, those options will be automatically appended to the search i.e "cut mp3 -"10 best" "

If this is not possible, its ok no problem.

**Comment by tiekoetter** [comment]
Please create your issue in the upstream repository (https://github.com/searxng/searxng/issues).
