### ISSUE TITLE
Bug: bing videos engine

### ISSUE THREAD

**Issue by nanchengbeix** [tiekoetter/searxng#24]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.06.06-ea0cddba (cceaf654)

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: timeout
  * Percentage: 0
  * Parameters: `()`
  * File name: `searx/search/processors/abstract.py:102`
  * Function: `handle_exception`
  * Code: `count_error(self.engine_name, exception_or_message)`

**Comment by tiekoetter** [comment]
Closing due to lack of replies.
