### ISSUE TITLE
Little but annoying bug | why removing all other skins? | not able to select from results

### ISSUE THREAD

**Issue by masterofobzene** [tiekoetter/searxng#25]
BUG:  
Search textbox has started to "select all" on first click. Annoying when I want to make quick corrections to the search words.

Skins:
Why where all the skin options removed? oscar theme was better IMO and did not suffer from the bugs above/below.

Select/Copy:
Cannot select text from search results leaving no other choice than clicking the results, go to the page and copy the required text there.

**Comment by tiekoetter** [comment]
Hi @masterofobzene,

Why oscar was removed: https://github.com/searxng/searxng/pull/1153
Select Copy issue: https://github.com/searxng/searxng/issues/794
I don't know what you exactly mean with your first issue/bug. Could you elaborate it a little more?

**Comment by tiekoetter** [comment]
@masterofobzene The oscar theme is highly broken. It will never be added to SearXNG again. Did you try developing for the oscar theme? If no how would you know how complex it is or isn't compared to the simple theme?

**Comment by tiekoetter** [comment]
@masterofobzene I still can't reproduce your error. I am using Chromium 102.0.5005.63

https://user-images.githubusercontent.com/77782671/173241159-40be4179-8910-4ee6-b981-b17efd67f461.mov

**Comment by tiekoetter** [comment]
@masterofobzene What do you mean it doesn't need further development? I would still like to help with the other issues because even searx.be will eventually drop oscar.
