### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by Turante** [tiekoetter/searxng#28]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.07.29-0cf53109 (c7cdaa72)

**How did you install SearXNG?**

**What happened?**

Changed settings to include Mojeek, did a search, got an error.

**How To Reproduce**

Same as above.

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 0
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Should be fixed.

See https://searx.tiekoetter.com/search?q=%21mjk+test+%3Aen
