### ISSUE TITLE
Bug: brave engine

### ISSUE THREAD

**Issue by HDark15** [tiekoetter/searxng#35]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.11.09-ee4475ff (7fd00581)

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineTooManyRequestsException
  * Percentage: 100
  * Parameters: `('Too many request',)`
  * File name: `searx/engines/xpath.py:199`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

Error
  * Error: httpx.TimeoutException
  * Percentage: 0
  * Parameters: `(None, None, None)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Currently not possible to fix. Refer to upstream https://github.com/searxng/searxng/issues/1651

This will be marked as won't fix until further notice.
