### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by aaronliu0130** [tiekoetter/searxng#39]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.11.18-1cdadf4b (db5573d3)

**What happened?**
When I search using the google engine I get a red error saying "Suspended: Access Denied"

**How To Reproduce**
Search anything with the google engine selected

**Expected behavior**
I get results

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/11874211/201423301-b3fb2bf1-6850-484c-a679-3dd4a0be2ebf.png)

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 15
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by aaronliu0130** [comment]
why is it that this always magically works soon after i post a bug report...

**Comment by tiekoetter** [comment]
What do you think?

**Comment by aaronliu0130** [comment]
Rate limit?

**Comment by tiekoetter** [comment]
No. I really don't know. I even disabled the mechanism in SearXNG which suspends the engines on errors but it keeps the state for whatever reason regardless. I can't find anything in the error logs and can't replicate it. My server is never really blocked as a simple restart of the SearXNG services fixes it.
Thank you for reporting but you don't have to write a report everytime (or add screenshots) you can just post it without any extra info. I hope this stops happening now as I did some other changes which will hopefully work.
