### ISSUE TITLE
Wikipedia links are redirected to "defaced", broken-layout wikiless

### ISSUE THREAD

**Issue by Talkless** [tiekoetter/searxng#44]
This is how Wikipedia pages looks like after redirected to Wikiless:
![image](https://user-images.githubusercontent.com/292191/220329258-936a222f-382c-471f-95ab-146cf8db2399.png)

Same issue with Firefox 102.8.0esr on Debian 11 bullseye, and with Firefox 109.0-1 on Debian Sid.

Something's wrong with CSS?

**Comment by tiekoetter** [comment]
@Talkless Please check again

**Comment by Talkless** [comment]
@tiekoetter looks OK now, thanks!
