### ISSUE TITLE
Infinite scrolling enabled, even if you have it disabled in options.

### ISSUE THREAD

**Issue by ElmorenohWTF** [tiekoetter/searxng#50]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

**What happened?**

The title is self-explanatory.
**How To Reproduce**

Do a search, the infinite scroll will be active even if you have it disabled in options.
**Expected behavior**

That the infinite scrolling was disabled, as I have set in options, and instead had several pages. I think infinite scrolling slows down the page load a lot.
**Screenshots & Logs**

**Additional context**

It is possible that it has something to do with the fact that I have all possible motors activated, although this should not happen anyway, regardless of how many motors I have activated.

**Comment by tiekoetter** [comment]
Hi @ElmorenohWTF,

I don't know what you mean by "I have all possible motors activated". Could you clarify this?

I can't reproduce your issue at the moment.

**Comment by ElmorenohWTF** [comment]
Hi, thank you for your amazing work maintaining the instance. I do not know the correct term, I mean that I have all the possible search engines that can be enabled within Searxng, enabled. For example, in the category of general search engines for the web, you can activate Google and duckduckgo and it will search in both at the same time.

**Comment by tiekoetter** [comment]
@ElmorenohWTF can you post your "URL to restore your preferences in another browser" (Preferences -> Cookies)?

**Comment by tiekoetter** [comment]
@ElmorenohWTF When I import these settings Infinite scroll is disabled. When I enable it after it works as it should and can be disabled again. Could you check if your issue is still present?

**Comment by ElmorenohWTF** [comment]
I have managed to disable the infinite scroll, but even so, when I do a search I get too many results (I have counted them and on that occasion I got 184 results on a single page), and they even make the page take longer to load. In Google for example, I only get 10 results per page.

**Comment by tiekoetter** [comment]
@ElmorenohWTF That is the expected behaviour when you enable _every_ engine.
