### ISSUE TITLE
DNS record no longer exists

### ISSUE THREAD

**Issue by se-jaeger** [tiekoetter/searxng#53]
Hi,

since this morning, it seems like the DNS record does no longer exist: https://www.nslookup.io/domains/searx.tiekoetter.com/dns-records/
(This is also the case for other *.tiekoetter.com sites)

**Comment by tiekoetter** [comment]
Are you running any DNS block lists? I can lookup the domains just fine (local, external and authoritative). Do you maybe have something like a Pi-hole running?

You could try running `dig +trace searx.tiekoetter.com` and see what the output is.

**Comment by se-jaeger** [comment]
Yes I do but tried multiple times today with and without. However, now everything is up and running again. So closing this. Thanks for you quick reply!
