### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by SecondCityOsD** [tiekoetter/searxng#56]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2024.11.27+342d32119 (8b54bb982)

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 95
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/engines/xpath.py:251`
  * Function: `response`
  * Code: `raise_for_httperror(resp)`

**Comment by tiekoetter** [comment]
Please fill out the issue template.
Until otherwise specified I will assume the issue is mojeek not giving results. This is "normal" because mojeek has all my proxies blocked.

Please reopen if your report is about something else.
