### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by ghost** [tiekoetter/searxng#9]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/tiekoetter/searxng
Branch: master
Version: 2022.03.13-cd92a7ea (1d821b28)

**How did you install SearXNG?**
 Via public host.
**What happened?**
 Could not find results, access denied.

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 10
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by tiekoetter** [comment]
Could you provide the used search-url?

**Comment by tiekoetter** [comment]
Works now.

https://searx.tiekoetter.com/search?q=%21mjk+test+%3Aen

<img width="1440" alt="Bildschirmfoto 2022-03-21 um 08 41 45" src="https://user-images.githubusercontent.com/77782671/159221011-ba1d063d-fa95-4ecf-a67f-9eadc4983615.png">
